import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { authOptions } from "@/lib/authOptions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // await authenticate();


  return (
    <>
      {children}
    </>

  );
}
